CREATE DATABASE chatbox DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;

USE chatbox;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) not null,
  photo VARCHAR(255) NOT NULL,
  CONSTRAINT PRIMARY KEY (id)
);

CREATE TABLE sms (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  mensagem TEXT NOT NULL,
  resposta TEXT,
  data_envio DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PRIMARY KEY (id),
  CONSTRAINT fk_user_sms FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);